### ISSUE TITLE
Ubuntu + e2guardian 4.02 = segfault

### ISSUE THREAD

**Issue by ktullanux** [e2guardian/e2guardian#199]
Hello guys!
Ubuntu 16.04 LTS (amd64, 4.8.0-45-generic)
Squid 4.0.18 + e2guardian 4.0.2 (deb or custom build - no difference)
If I open a http good site - everything is ok. If open http porn site - take segfault. 
On 3.5.1 works fine.
Configuration files are original. No blacklists.

```
Apr  2 17:32:54 xxx e2guardian[23952]: Started sucessfully.
Apr  2 17:33:09 xxx kernel: [ 4043.114862] e2guardian[23987]: segfault at 0 ip 000000000046d42f sp 00007f889aa59fe0 error 4 in e2guardian[400000+e6000]
Apr  2 17:33:09 xxx e2guardian[24163]: No e2guardian process found.
Apr  2 17:33:09 xxx systemd[1]: e2guardian.service: Control process exited, code=exited status=1
Apr  2 17:33:09 xxx systemd[1]: e2guardian.service: Unit entered failed state.
Apr  2 17:33:09 xxx systemd[1]: e2guardian.service: Failed with result 'exit-code'.
Apr  2 17:33:23 xxx systemd[1]: Stopped E2guardian Web filtering.
Apr  2 17:33:23 xxx systemd[1]: Starting E2guardian Web filtering...
Apr  2 17:33:23 xxx systemd[1]: Started E2guardian Web filtering.
Apr  2 17:33:23 xxx e2guardian[24185]: Started sucessfully.
Apr  2 17:33:28 xxx e2guardian[24185]: 51309 No header recd from client - errno: 0
Apr  2 17:33:29 xxx e2guardian[24185]: 51310 No header recd from client - errno: 0
Apr  2 17:33:30 xxx kernel: [ 4064.371752] e2guardian[24190]: segfault at 0 ip 000000000046d42f sp 00007fd9d14a8fe0 error 4 in e2guardian[400000+e6000]
Apr  2 17:33:30 xxx e2guardian[24399]: No e2guardian process found.
Apr  2 17:33:30 xxx systemd[1]: e2guardian.service: Control process exited, code=exited status=1
Apr  2 17:33:30 xxx systemd[1]: e2guardian.service: Unit entered failed state.
Apr  2 17:33:30 xxx systemd[1]: e2guardian.service: Failed with result 'exit-code'.
```

**Comment by Kenny690** [comment]
Debian Stretch.
I can confirm it. 
I'm getting a lot of

`Apr  3 09:03:16 osiris e2guardian[10818]: 51082 No header recd from client at 10.20.30.16 - errno: 0`

Which causes sites to load nearly 10 sec. 
And, as usual, this:

```
Apr  3 09:07:15 osiris e2guardian[12134]: NTLM - Invalid message of length 0, message was:
Apr  3 09:07:15 osiris e2guardian[12134]: Auth plugin returned error code: -3
```

**Comment by fredbcode** [comment]
I pushed a new package, please make a try 
Thanks

**Comment by Kenny690** [comment]
Still getting segfaults.

**Comment by fredbcode** [comment]
Kenny always on Stretch ? Works well here with Jessie 64 bits

**Comment by fredbcode** [comment]
@ktullanux and now ? Can your share your config files please ?

**Comment by Kenny690** [comment]
Yep. It's our main and only server.

**Comment by fredbcode** [comment]
Do you have all that libraries 

	linux-vdso.so.1 (0x00007ffd7a717000)
	libpcreposix.so.3 => /usr/lib/x86_64-linux-gnu/libpcreposix.so.3 (0x00007fb0de055000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fb0ddde7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb0ddbca000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb0dd9af000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb0dd6a4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb0dd3a3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb0dd18d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb0dcde2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb0de258000)

**Comment by fredbcode** [comment]
Specially libevent-pthreads

**Comment by Kenny690** [comment]
Seems like yes.
`root@Osiris:~/e2guardian-4.0# ldd /usr/sbin/e2guardian
        linux-vdso.so.1 (0x00007ffc045e0000)
        libpcreposix.so.3 => /usr/lib/x86_64-linux-gnu/libpcreposix.so.3 (0x00007f2c7b4b2000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f2c7b23f000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2c7b022000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2c7ae08000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2c7aa86000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2c7a780000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2c7a569000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2c7a1cb000)
        /lib64/ld-linux-x86-64.so.2 (0x0000562f0877a000)
`

**Comment by fredbcode** [comment]
I pushed a new binary without specific optimisation, please remove e2guardian with purge 
apt-get remove e2guardian --purge and install 

e2guardian must show this:
e2guardian -v
e2guardian 4.0.2

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes'

**Comment by fredbcode** [comment]
Hum I'm not using SSLMITM right now, and you ?

**Comment by Kenny690** [comment]
Still getting segfaults.
I'm using it. I'll try to turn it off.

**Comment by fredbcode** [comment]
Yes please, if you can try with a configuration very close to default and change step by step to find where the issue is 

Thanks

**Comment by Kenny690** [comment]
Tried totally clean isntallation. 
Everything was fine, but after I removed comment at 
#badboys.com
and tried to go to that website - I've got segfault.

**Comment by fredbcode** [comment]
Yes, there is a problem I will investigate

**Comment by fredbcode** [comment]
Ok, I found where the problem is and why there is no segfault here !
The problem is related with the default page value, if I'm using htmltemplate = 'my_page.htm' no problem (of course my_page.htm must exist) 

I hope I will find the time to take a look this week

**Comment by Kenny690** [comment]
Doesn't work with me. I even tried to set reportinglevel = 0, but still catching that:

```
Apr  3 17:09:36 osiris kernel: [50930.563809] e2guardian[2990]: segfault at 8 ip 0000000000498838 sp 00007f04e20eef80 error 4 in e2guardian[400000+e5000]
Apr  3 17:09:36 osiris systemd[1]: e2guardian.service: Main process exited, code=killed, status=11/SEGV
Apr  3 17:09:36 osiris systemd[1]: e2guardian.service: Unit entered failed state.
Apr  3 17:09:36 osiris systemd[1]: e2guardian.service: Failed with result 'signal'.

```

**Comment by ktullanux** [comment]
Purge and install new deb. Same problem.
```
root@campus-edu:/var/log/e2guardian# e2guardian -v
e2guardian 4.0.2

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes'
```
systemd
```
Apr  3 14:57:01 campus-edu e2guardian[28215]: Started sucessfully.
Apr  3 14:57:25 campus-edu e2guardian[28215]: 54261 No header recd from client at 10.10.14.14 - errno: 0
Apr  3 14:57:40 campus-edu kernel: [85701.547145] e2guardian[28310]: segfault at fffffffffffffff8 ip 00007f004d4f33cb sp 00007eff9bfcb960 error 5 in libstdc++.so.6.0.21[7f004d423000+172000]
Apr  3 14:57:40 campus-edu systemd[1]: e2guardian.service: Main process exited, code=killed, status=11/SEGV
Apr  3 14:57:40 campus-edu systemd[1]: e2guardian.service: Unit entered failed state.
Apr  3 14:57:40 campus-edu systemd[1]: e2guardian.service: Failed with result 'signal'.

```
/var/log/syslog
```
Apr  3 14:56:55 campus-edu systemd[1]: Starting E2guardian Web filtering...
Apr  3 14:57:01 campus-edu systemd[1]: Started E2guardian Web filtering.
Apr  3 14:57:01 campus-edu e2guardian[28215]: Started sucessfully.
Apr  3 14:57:25 campus-edu e2guardian[28215]: 54261 No header recd from client at 10.10.14.14 - errno: 0
Apr  3 14:57:40 campus-edu kernel: [85701.547145] e2guardian[28310]: segfault at fffffffffffffff8 ip 00007f004d4f33cb sp 00007eff9bfcb960 error 5 in libstdc++.so.6.0.21[7f004d423000+172000]
Apr  3 14:57:40 campus-edu systemd[1]: e2guardian.service: Main process exited, code=killed, status=11/SEGV
Apr  3 14:57:40 campus-edu systemd[1]: e2guardian.service: Unit entered failed state.
Apr  3 14:57:40 campus-edu systemd[1]: e2guardian.service: Failed with result 'signal'.

```

e2guardian.conf
```
languagedir = '/usr/share/e2guardian/languages'
language = 'russian-1251'
loglevel = 3
logexceptionhits = 2
logfileformat = 1
loglocation = '/var/log/e2guardian/access.log'
dstatlocation = '/var/log/e2guardian/dstats.log'
filterip =
filterports = 8080
proxyip = 127.0.0.1
proxyport = 3130
proxytimeout = 5
proxyexchange = 61
pcontimeout = 55
usecustombannedimage = on
custombannedimagefile = '/usr/share/e2guardian/transparent1x1.gif'
usecustombannedflash = on
custombannedflashfile = '/usr/share/e2guardian/blockedflash.swf'
filtergroups = 1
filtergroupslist = '/etc/e2guardian/lists/filtergroupslist'
bannediplist = '/etc/e2guardian/lists/bannediplist'
exceptioniplist = '/etc/e2guardian/lists/exceptioniplist'
showweightedfound = on
weightedphrasemode = 2
urlcachenumber = 1000  **NOT YET IMPLEMENTED
urlcacheage = 900  **NOT YET IMPLEMENTED
scancleancache = on  **NOT YET IMPLEMENTED
phrasefiltermode = 2
preservecase = 0
hexdecodecontent = off
forcequicksearch = off
reverseaddresslookups = off
reverseclientiplookups = off
logclienthostnames = off
maxcontentfiltersize = 256
maxcontentramcachescansize = 2000
maxcontentfilecachescansize = 20000
filecachedir = '/tmp'
deletedownloadedtempfiles = on
initialtrickledelay = 20
trickledelay = 10
downloadmanager = '/etc/e2guardian/downloadmanagers/default.conf'
contentscannertimeout = 60
contentscanexceptions = off
recheckreplacedurls = off
forwardedfor = on
usexforwardedfor = on
xforwardedforfilterip = 127.0.0.1 
logconnectionhandlingerrors = on
httpworkers = 500
maxips = 0  **NOT YET IMPLEMENTED
nodaemon = off
nologger = off
logadblocks = off
loguseragent = off
softrestart = off
enablessl = off
```
squid.conf
```
acl localnet src 10.10.14.0/24
acl localnet src 10.10.15.0/24
acl localnet src 127.0.0.1
follow_x_forwarded_for allow all
acl SSL_ports port 443
acl Safe_ports port 80		# http
acl Safe_ports port 21		# ftp
acl Safe_ports port 443		# https
acl Safe_ports port 70		# gopher
acl Safe_ports port 210		# wais
acl Safe_ports port 1025-65535	# unregistered ports
acl Safe_ports port 280		# http-mgmt
acl Safe_ports port 488		# gss-http
acl Safe_ports port 591		# filemaker
acl Safe_ports port 777		# multiling http
acl CONNECT method CONNECT
acl all src all 
no_cache deny all
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localhost manager
http_access deny manager
http_access allow localnet
http_access allow localhost
http_access deny all
http_port 3128 intercept
http_port 3130
https_port 3129 intercept ssl-bump options=ALL:NO_SSLv3:NO_SSLv2 connection-auth=off cert=/etc/squid/squidCA.pem
always_direct allow all
sslproxy_cert_error allow all
sslproxy_flags DONT_VERIFY_PEER
acl blocked ssl::server_name  "/etc/squid/blocked_https.txt"
acl step1 at_step SslBump1
ssl_bump peek step1
ssl_bump terminate blocked 
ssl_bump splice all
sslcrtd_program /lib/squid/security_file_certgen -s /var/spool/squid/ssl_db -M 4MB
coredump_dir /var/spool/squid
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
cache_dir ufs /var/spool/squid 2048 16 256
maximum_object_size 61440 KB
minimum_object_size 3 KB
cache_swap_low 90
cache_swap_high 95
maximum_object_size_in_memory 512 KB
memory_replacement_policy lru
logfile_rotate 4

```

**Comment by fredbcode** [comment]
htmltemplate must be in groupe file (e2guardianf1.conf not e2guardian.conf)
Where your language file is 
Eg:

languagedir = '/etc/e2guardian/languages' -> e2guardian.conf
language = 'french' -> e2guardian.conf -> e2guardian.conf
htmltemplate = 'groupe1.htm' -> e2guardian**f1**.conf

So the file must be in /etc/e2guardian/languages/french/groupe1.htm with e2guardian as owner

**Comment by ktullanux** [comment]
It works!
Now check)

**Comment by fredbcode** [comment]
Ok so there is something wrong with it, seems like htlm_template is not initialized in FOptionContainer.cpp or something like that

**Comment by Kenny690** [comment]
Erm... Just something strange is happening.

e2guardian.conf:

```
languagedir = '/usr/share/e2guardian/languages'
language = 'russian-koi8-r'
loglevel = 3
logexceptionhits = 2
logfileformat = 1
filterip = 10.20.30.1
filterports = 8080
proxyip = 10.20.30.1
proxyport = 8081
proxytimeout = 20
proxyexchange = 20
pcontimeout = 55
usecustombannedimage = on
custombannedimagefile = '/usr/share/e2guardian/transparent1x1.gif'
usecustombannedflash = on
custombannedflashfile = '/usr/share/e2guardian/blockedflash.swf'
filtergroups = 1
filtergroupslist = '/etc/e2guardian/lists/filtergroupslist'
bannediplist = '/etc/e2guardian/lists/bannediplist'
exceptioniplist = '/etc/e2guardian/lists/exceptioniplist'
showweightedfound = on
weightedphrasemode = 2
urlcachenumber = 1000  **NOT YET IMPLEMENTED
urlcacheage = 900  **NOT YET IMPLEMENTED
scancleancache = on  **NOT YET IMPLEMENTED
phrasefiltermode = 2
preservecase = 0
hexdecodecontent = on
forcequicksearch = on
reverseaddresslookups = on
reverseclientiplookups = on
logclienthostnames = on
maxcontentfiltersize = 512000
maxcontentramcachescansize = 512000
maxcontentfilecachescansize = 512000
filecachedir = '/tmp'
deletedownloadedtempfiles = on
initialtrickledelay = 20
trickledelay = 10
downloadmanager = '/etc/e2guardian/downloadmanagers/fancy.conf'
downloadmanager = '/etc/e2guardian/downloadmanagers/default.conf'
contentscanner = '/etc/e2guardian/contentscanners/clamdscan.conf'
contentscannertimeout = 20
contentscanexceptions = off
authplugin = '/etc/e2guardian/authplugins/proxy-ntlm.conf'
authplugin = '/etc/e2guardian/authplugins/ip.conf'
recheckreplacedurls = off
forwardedfor = on
usexforwardedfor = on
logconnectionhandlingerrors = on
httpworkers = 400
maxips = 0  **NOT YET IMPLEMENTED
nodaemon = off
nologger = off
logadblocks = on
loguseragent = off
softrestart = off
enablessl = on
```

https://www.diffchecker.com/dKRo5eOg

Left is OK (even without  htmltemplate set up), but right is causing segfault.

**Comment by fredbcode** [comment]
Step by step, can you confirm that the first bug is fixed ?
I pushed a new package for debian

**Comment by Kenny690** [comment]
Step-by-step...
What have I did: 
```
1. apt-get remove e2guardian --purge'
2. wget https://github.com/e2guardian/e2guardian/archive/v4.0.zip
3. unzip v4.0.zip
4. cd e2guardian-4.0
5. ./autogen.sh && ./configure '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--enable-locallists=yes' && make
6. e2guardian
```
Result:
```
root@Osiris:~/e2guardian-4.0# e2guardian
Error reading file /etc/e2guardian/lists/sslsiteregexplist: Нет такого файла или каталога
Error opening sslsiteregexplist
Error opening filter group config: /etc/e2guardian/e2guardianf1.conf
Error in reading filter group files
Error reading filter group conf file(s).
Error parsing the e2guardian.conf file or other e2guardian configuration files
```

**Comment by Kenny690** [comment]
Next steps:

```
1. touch /etc/e2guardian/lists/sslsiteregexplist
2. e2guardian
```

Result:

```
root@Osiris:~/e2guardian-4.0# e2guardian
Unable to getpwnam() - does the proxy user exist?
Proxy user looking for is 'e2guardian'
```

**Comment by fredbcode** [comment]
Ah ok , please you must export the branch with git pull or use the package 
The zip still the same

**Comment by Kenny690** [comment]
Rawr... Ok. :D
I removed and cleaned up everything.
Then:

```
1. wget https://github.com/e2guardian/e2guardian/releases/download/v4.0beta2/e2guardian_4.0.2_jessie_ubuntu16.04_amd64.deb
2. e2guardian
```

I've got:

```
root@Osiris:~# e2guardian
I seem to be running already!
```

So installation is working OK.

**Comment by fredbcode** [comment]
Ok great so I will close this ticket, please test and open a new bug if needed
