### ISSUE TITLE
SSLMITM on v4.0

### ISSUE THREAD

**Issue by Kenny690** [e2guardian/e2guardian#200]
Everything works fine until I turn on SSLMITM. Then I'm getting segfaults on bad sites. Configs are default. just enablessl = on and sslmitm = on.

**Comment by Kenny690** [comment]
If have found the problem. Certificates was wrong.

**Comment by Kenny690** [comment]
Although, I'm getting a lot of:
`No header recd from client at 10.20.30.17 - errno: 0`

**Comment by fredbcode** [comment]
I guess e2 should not segfault

**Comment by fredbcode** [comment]
Can you share your "wrong" certificate ?

**Comment by Kenny690** [comment]
Wrong certificate = no certificate at all. :D
I had that:

#cacertificatepath = '/etc/e2guardian/my_rootCA.crt'
#caprivatekeypath = '/etc/e2guardian/private_root.pem'
#certprivatekeypath = '/etc/e2guardian/private_cert.pem'
#generatedcertpath = '/etc/e2guardian/generatedcerts/'

This caused segfault, but after I removed '#' - it started well.

**Comment by fredbcode** [comment]
Ok so there is a bug, thanks

**Comment by Kenny690** [comment]
LOL, I didn't expect that. :D 
Anyway, If I could help you, just ask. :)

**Comment by fredbcode** [comment]
In ideal world e2 must never crash, a warning message will appear

**Comment by fredbcode** [comment]
Ok fixed, can you confirm there is no problem with SSLMITM at start please ? (package pushed)

**Comment by ktullanux** [comment]
install latest deb and try sslmitm
```
openssl genrsa 4096 > private_root.pem
openssl req -new -x509 -days 3650 -key private_root.pem -out my_rootCA.crt
openssl x509 -in my_rootCA.crt -outform DER -out my_rootCA.der
openssl genrsa 4096 > private_cert.pem
chown -R e2guardian:e2guardian /etc/e2guardian/certs
```

and take 
```
Apr 04 21:08:13 campus-edu e2guardian[18293]: Couldn't open ca private key
Apr 04 21:08:13 campus-edu systemd[1]: e2guardian.service: Control process exited, code=exited status=1
Apr 04 21:08:13 campus-edu systemd[1]: Failed to start E2guardian Web filtering.
```
e2guardian.conf
```
languagedir = '/usr/share/e2guardian/languages'
language = 'russian-1251'
loglevel = 3
logexceptionhits = 2
logfileformat = 1
loglocation = '/var/log/e2guardian/access.log'
dstatlocation = '/var/log/e2guardian/dstats.log'
filterip =
filterports = 8080
proxyip = 127.0.0.1
proxyport = 3130
 # This is a connection timeout
 # If proxy is remote you may need to increase this to 10 or more.
proxytimeout = 5
proxyexchange = 61
pcontimeout = 55
usecustombannedimage = on
custombannedimagefile = '/usr/share/e2guardian/transparent1x1.gif'
usecustombannedflash = on
custombannedflashfile = '/usr/share/e2guardian/blockedflash.swf'
filtergroups = 1
filtergroupslist = '/etc/e2guardian/lists/filtergroupslist'
bannediplist = '/etc/e2guardian/lists/bannediplist'
exceptioniplist = '/etc/e2guardian/lists/exceptioniplist'
showweightedfound = on
weightedphrasemode = 2
urlcachenumber = 1000  **NOT YET IMPLEMENTED
urlcacheage = 900  **NOT YET IMPLEMENTED
scancleancache = on  **NOT YET IMPLEMENTED
phrasefiltermode = 2
preservecase = 0
hexdecodecontent = off
forcequicksearch = off
reverseaddresslookups = off
reverseclientiplookups = off
logclienthostnames = off
maxcontentfiltersize = 256
maxcontentramcachescansize = 2000
maxcontentfilecachescansize = 20000
filecachedir = '/tmp'
deletedownloadedtempfiles = on
initialtrickledelay = 20
trickledelay = 10
downloadmanager = '/etc/e2guardian/downloadmanagers/default.conf'
contentscannertimeout = 60
contentscanexceptions = off
recheckreplacedurls = off
forwardedfor = off
usexforwardedfor = off
logconnectionhandlingerrors = on
httpworkers = 500
maxips = 0  **NOT YET IMPLEMENTED
nodaemon = off
nologger = off
logadblocks = off
loguseragent = off
softrestart = off
enablessl = on
cacertificatepath = '/etc/e2guardian/certs/my_rootCA.crt'
caprivatekeypath = '/etc/e2guardian/certs/pricate_root.pem'
certprivatekeypath = '/etc/e2guardian/certs/private_cert.pem'
generatedcertpath = '/etc/e2guardian/certs'
```

e2guardianf1.conf
```
groupname = 'no_mame_group'
ssllegacylogic = off
bannedphraselist = '/etc/e2guardian/lists/bannedphraselist'
weightedphraselist = '/etc/e2guardian/lists/weightedphraselist'
exceptionphraselist = '/etc/e2guardian/lists/exceptionphraselist'
bannedsitelist = '/etc/e2guardian/lists/bannedsitelist'
greysitelist = '/etc/e2guardian/lists/greysitelist'
bannedsslsitelist = '/etc/e2guardian/lists/bannedsslsitelist'
greysslsitelist = '/etc/e2guardian/lists/greysslsitelist'
exceptionsitelist = '/etc/e2guardian/lists/exceptionsitelist'
bannedurllist = '/etc/e2guardian/lists/bannedurllist'
greyurllist = '/etc/e2guardian/lists/greyurllist'
exceptionurllist = '/etc/e2guardian/lists/exceptionurllist'
exceptionregexpurllist = '/etc/e2guardian/lists/exceptionregexpurllist'
bannedregexpurllist = '/etc/e2guardian/lists/bannedregexpurllist'
picsfile = '/etc/e2guardian/lists/pics'
contentregexplist = '/etc/e2guardian/lists/contentregexplist'
urlregexplist = '/etc/e2guardian/lists/urlregexplist'
refererexceptionsitelist = '/etc/e2guardian/lists/refererexceptionsitelist'
refererexceptionurllist = '/etc/e2guardian/lists/refererexceptionurllist'
embededreferersitelist = '/etc/e2guardian/lists/embededreferersitelist'
embededrefererurllist = '/etc/e2guardian/lists/embededrefererurllist'
urlredirectregexplist = '/etc/e2guardian/lists/urlredirectregexplist'
sslsiteregexplist = '/etc/e2guardian/lists/sslsiteregexplist'
!! Not compiled !! authexceptionsitelist = '/etc/e2guardian/lists/authexceptionsitelist'
!! Not compiled !! authexceptionurllist = '/etc/e2guardian/lists/authexceptionurllist'
blockdownloads = off
exceptionextensionlist = '/etc/e2guardian/lists/exceptionextensionlist'
exceptionmimetypelist = '/etc/e2guardian/lists/exceptionmimetypelist'
bannedextensionlist = '/etc/e2guardian/lists/bannedextensionlist'
bannedmimetypelist = '/etc/e2guardian/lists/bannedmimetypelist'
exceptionfilesitelist = '/etc/e2guardian/lists/exceptionfilesitelist'
exceptionfileurllist = '/etc/e2guardian/lists/exceptionfileurllist'
maxuploadsize = -1
headerregexplist = '/etc/e2guardian/lists/headerregexplist'
bannedregexpheaderlist = '/etc/e2guardian/lists/bannedregexpheaderlist'
addheaderregexplist = '/etc/e2guardian/lists/addheaderregexplist'
naughtynesslimit = 50
categorydisplaythreshold = 0
embeddedurlweight = 0
bypass = 0
bypasskey = ''
infectionbypass = 0
infectionbypasskey = ''
infectionbypasserrorsonly = on
disablecontentscan = off
deepurlanalysis = off
reportinglevel = 3
htmltemplate = 'custom.html'
usesmtp = off   #NOT YET TESTED
mailfrom = ''
avadmin = ''
contentadmin = ''
avsubject = 'e2guardian virus block'
contentsubject = 'e2guardian violation'
notifyav = off
notifycontent = off
thresholdbyuser = off
violations = 0
threshold = 0
sslcertcheck = off
sslmitm = on
onlymitmsslgrey = off
mitmcheckcert = on
nocheckcertsitelist = '/etc/e2guardian/lists/nocheckcertsitelist'
```

**Comment by fredbcode** [comment]
Nothing before ?

Apr 04 21:08:13 campus-edu e2guardian[18293]: Couldn't open ca private key


----- Artem Lukyanov <notifications@github.com> a écrit :

**Comment by Kenny690** [comment]
Look there:
caprivatekeypath = '/etc/e2guardian/certs/pricate_root.pem'

Not pricate. Private.

**Comment by ktullanux** [comment]
my mistake!
yep, no pri**c**ate

**Comment by fredbcode** [comment]
#daemonuser = '@DGPROXYUSER@'
#daemongroup = '@DGPROXYGROUP@'

Are you sure that e2guardian is running with daemonuser e2guardian ?


----- Artem Lukyanov <notifications@github.com> a écrit :

**Comment by fredbcode** [comment]
Ok great ! Thanks Kenny

**Comment by Kenny690** [comment]
Still getting segfaults, but with no specific reason. Access.log has no unusual strings. It happens once per day randomly.
Trying to investigate it.

**Comment by fredbcode** [comment]
Are you sure that you are using the latest github pull ?

**Comment by Kenny690** [comment]
Tried to comment certificates and get "sslmitm requires certificates" instead of segfault. So seems like yes.

**Comment by Kenny690** [comment]
I can't do a search on yandex.ru and can't enter portal.office.com.
Yandex gave me "can't connect to proxy server and I had in logs this:

```
Apr  6 14:26:04 osiris e2guardian[7659]:  -connection handler caught an exception std::exception
Apr  6 14:26:04 osiris e2guardian[7659]:  -connection handler caught an exception std::exception
Apr  6 14:26:04 osiris e2guardian[7659]: 49548 Error sending to client 3648 Client at 10.20.30.50 has disconnected - errno: 0
Apr  6 14:26:04 osiris e2guardian[7659]: 49548 Error sending to client 3648 cant read proxy Connection - errno: 0
Apr  6 14:26:04 osiris e2guardian[7659]: 49549 Error sending to client 3648 Client at 10.20.30.50 has disconnected - errno: 0
Apr  6 14:26:04 osiris e2guardian[7659]: 49549 Error sending to client 3648 cant read proxy Connection - errno: 0
```
And second give me code 400 and the same in logs.

**Comment by fredbcode** [comment]
@ktullanux did you have the same issue than Kenny ?

**Comment by Kenny690** [comment]
It appears even with turned off "enablessl"

**Comment by ktullanux** [comment]
@fredbcode on next week, i can check this

**Comment by spikedrba** [comment]
fwiw I'm not getting any of these errors. I'm running ubuntu xenial and I've tried both with v4 installed from the v4 branch and v4.0.2 installed from the .deb. In neither case I've had these problems, I can connect to yandex, etc, all https sites are correctly filtered.

@fredbcode one thing I noticed, in the deb pkg there is indeed a enablessl directive to turn on in the main config, however I did not find such option in the sources code (nor I needed it, it just worked when I turned it on in the group). what am I missing?

**Comment by fredbcode** [comment]
@spikedrba Yes this is fixed now, but I have not pushed a new package yet

**Comment by Kenny690** [comment]
I reinstalled it and reconfigured again. Still getting from time to time this:
```
Apr 10 12:00:17 osiris e2guardian[8050]:  -connection handler caught an exception std::bad_alloc
Apr 10 12:00:20 osiris e2guardian[8050]: 54098 No header recd from client at 10.20.30.73 - errno: 0
Apr 10 12:00:22 osiris e2guardian[8050]: 51011 No header recd from client at 10.20.30.148 - errno: 0
Apr 10 12:01:25 osiris e2guardian[8050]: 49612 No header recd from client at 10.20.30.113 - errno: 0
```
But seems like everythings works ok.

**Comment by fredbcode** [comment]
@Kenny690  "No header recd from client at" -> This can be a software in conflict with HTTP standards
I'm not worrying about

Someone can tell me if some lines in squid log are recorded with 127.0.0.1 and no the user IP ?
grep 127.0.0.1 /var/log/squid/access.log 
Of course if you are using X-Forwarded-for

**Comment by Kenny690** [comment]
I tried to test it but found some problem.
"/etc/init.d/e2guardian restart" and "service e2guardian restart" giving me errors:

```
апр 10 13:15:36 Osiris e2guardian[28558]: I seem to be running already!
апр 10 13:15:36 Osiris e2guardian[28558]: I seem to be running already!
апр 10 13:15:36 Osiris systemd[1]: e2guardian.service: Control process exited, code=exited status=1
апр 10 13:15:36 Osiris systemd[1]: Failed to start E2guardian Web filtering.
```
Seems like they can't stop it.

```
root@Osiris:~# /etc/init.d/e2guardian stop
[ ok ] Stopping e2guardian (via systemctl): e2guardian.service.
root@Osiris:~# e2guardian
I seem to be running already!
```

**Comment by fredbcode** [comment]
Now it's "system e2guardian stop"
But maybe after some tests your system is unstable, I guess you can try to reboot and after that check with

system e2guardian stop
system e2guardian start

Do you have the same starting script ? https://github.com/e2guardian/e2guardian/blob/master/data/scripts/e2guardian.service.in in /etc/systemd/system

**Comment by Kenny690** [comment]
```
root@Osiris:~# system e2guardian stop
-bash: system: command not found
```
I have different script.
```
[Unit]
Description=E2guardian Web filtering
After=network.target

[Service]
Type=forking
LimitNOFILE=65535
ExecStart=/usr/sbin/e2guardian
ExecReload=/usr/sbin/e2guardian -r
[Install]
WantedBy=multi-user.target
```

**Comment by fredbcode** [comment]
Oh sorry "service e2guardian stop"

**Comment by ktullanux** [comment]
everything is ok, but 
https://maps.yandex.ru
```
Apr 10 11:51:16 campus-edu e2guardian[7567]: 51341 No header recd from client at 10.10.14.14 - errno: 0
Apr 10 11:51:16 campus-edu e2guardian[7567]: 51321 No header recd from client at 10.10.14.14 - errno: 0
Apr 10 11:51:16 campus-edu e2guardian[7567]: 51347 No header recd from client at 10.10.14.14 - errno: 0
Apr 10 11:51:16 campus-edu e2guardian[7567]: 51339 No header recd from client at 10.10.14.14 - errno: 0
Apr 10 11:51:16 campus-edu e2guardian[7567]: 51331 No header recd from client at 10.10.14.14 - errno: 0
Apr 10 11:51:16 campus-edu e2guardian[7567]: 51342 No header recd from client at 10.10.14.14 - errno: 0

```

**Comment by Kenny690** [comment]
@spikedrba can you try maps.yandex.ru?

**Comment by Kenny690** [comment]
@fredbcode 
```
root@Osiris:~# service e2guardian restart
Job for e2guardian.service failed because the control process exited with error code.
See "systemctl status e2guardian.service" and "journalctl -xe" for details.
```
journalctl -xe:

```
апр 10 14:00:57 Osiris e2guardian[13063]: I seem to be running already!
апр 10 14:00:57 Osiris e2guardian[13063]: I seem to be running already!
апр 10 14:00:57 Osiris systemd[1]: e2guardian.service: Control process exited, code=exited status=1
апр 10 14:00:57 Osiris systemd[1]: Failed to start E2guardian Web filtering.
```

**Comment by fredbcode** [comment]
@Kenny690 after a reboot ?

**Comment by fredbcode** [comment]
@ktullanux but the website works ?

**Comment by Kenny690** [comment]
@fredbcode yes, after reboot.
I have the same problem as @ktullanux. Website doesn't works.

**Comment by ktullanux** [comment]
@fredbcode search and maps not work

**Comment by ktullanux** [comment]
open https://yandex.ru/images/
`2017.4.10 12:14:16 - 10.10.14.14 https://yandex.ru/images/ *DENIED*    .50 : 85 ((member,  galler)+(proxy, block)+(proxy, filter)+- dns + fitte+ porn+ porno+-main+-partnership+porno+-social+-transparent+-troubleshooting) GET 128027 85 Pornography (Norwegian), Proxies, Pornography, Pornography (German) 1 403 text/html - no_mame_group - - - - -`

**Comment by fredbcode** [comment]
Ah ! So there is no bug here the filter rules are restrictive by default

**Comment by Kenny690** [comment]
@fredbcode nope. I have no restrictions on that site. More than that it was working on 3.5.4.
I turned off sslmitm and maps.yandex.ru and yandex.ru/search works now. But I need sslmitm.

**Comment by fredbcode** [comment]
There was a message from @ktullanux with log lines from e2guardian, Yandex was denied 
This message is removed 

Kenny do you something in e2guardian log file about yandex ?

**Comment by ktullanux** [comment]
yep, if sslmitm = off - everything works fine: Yandex search and maps

**Comment by fredbcode** [comment]
With "on" you have this "2017.4.10 12:14:16 - 10.x.x.x https://yandex.ru/images/ *DENIED*"

**Comment by Kenny690** [comment]
@fredbcode we talked about that. I pointed him on naughtynesslimit. :)
I just don't have anything about maps.yandex.ru and getting ERR_CONTENT_DECODING_FAILED in chrome.

**Comment by fredbcode** [comment]
Usually, It happens when a HTTP request's headers claim that the content is gzip encoded, but it isn't. Turn off gzip encoding setting or make sure the content is in fact encode

Maybe we have a problem with SSLMITM and gzip content

**Comment by fredbcode** [comment]
To confirm, can you make a try with IE and Firefox please

**Comment by Kenny690** [comment]
IE doesn't work as well. Nothing's in squid's access.log, except TCP_TUNNEL/200 on yandex.ru and totally nothing's in e2guadian's access.log.

**Comment by Kenny690** [comment]
@fredbcode and, BTW, e2guardian doesn't start by itself on reboot and it can't be stopped by systemctl. Only killall works.

**Comment by ktullanux** [comment]
same with IE and Firefox

**Comment by fredbcode** [comment]
There is ERR_CONTENT_DECODING_FAILED also in IE and FF ?
@Kenny690 Ubuntu 16.04 ? Can you try "systemctl enable e2guardian" 
Are you using deb package ? If not can you post your compilation option please

**Comment by ktullanux** [comment]
IE "Прокси-сервер не отвечает" - "The proxy server does not respond"
Firefox "Ошибка в типе содержимого
Страница, которую вы пытаетесь просмотреть, не может быть показана, так как она использует неверную или неподдерживаемую форму компрессии." -  "Error in content type
The page you are trying to view can not be displayed because it uses an invalid or unsupported compression form. "

**Comment by Kenny690** [comment]
@fredbcode same as ktullanux has.
I have debian stretch and I'm using deb package.

```
root@Osiris:~# systemctl enable e2guardian
Synchronizing state of e2guardian.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable e2guardian
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the unit is meant to be enabled with some
   instance name specified.
```

**Comment by fredbcode** [comment]
@Kenny690 can try to remove this part 

[Install]
WantedBy=multi-user.target

And after retry "systemctl enable e2guardian"

[Unit]
Description=E2guardian Web filtering
After=network.target

[Service]
Type=forking
LimitNOFILE=65535
ExecStart=/usr/sbin/e2guardian
ExecReload=/usr/sbin/e2guardian -r

**Comment by Kenny690** [comment]
https://github.com/e2guardian/e2guardian/blob/master/data/scripts/e2guardian.service.in
I copied this. There was no WantedBy=multi-user.target. After I added this line - it started to work.

**Comment by fredbcode** [comment]
What do you when it restart ?

**Comment by fredbcode** [comment]
Maybe you could play with this file, in comparison with others, sorry I'm not running strech here

**Comment by fredbcode** [comment]
@Kenny690 @ktullanux Can you make quick test in src/HTTPHeader.cpp comment the line 974 this line contains (*i) = modifyEncodings(*i) + "\r";

In c++ comment is like this //

So 
// (*i) = modifyEncodings(*i) + "\r";

After that, rebuild and test yandex 

Thanks

**Comment by ktullanux** [comment]
Built with: '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes'

and replace /usr/sbin/e2guardian to new /usr/sbin/e2guardian from build with comment line 974
and take in all http or https sites
```
2017.4.10 16:04:34 - 10.10.14.14 https://yandex.ru *DENIED*       :- GET 0 0 Banned User 1 403 - - no_mame_group - - - - -
2017.4.10 16:04:34 - 10.10.14.14 https://yandex.ru/favicon.ico *DENIED*       :- GET 0 0 Banned User 1 403 - - no_mame_group - - - - -
```

**Comment by fredbcode** [comment]
Hum, ok can you make a try with also the line before commented 
The line with "Accept-Encoding"

**Comment by ktullanux** [comment]
comment 
// (*i) = "Accept-Encoding:" + i->after(":");
// (*i) = modifyEncodings(*i) + "\r";
build and take same

**Comment by fredbcode** [comment]
Ok so remove thanks

**Comment by fredbcode** [comment]
@ktullanux or @Kenny690 
Can you share with me, your complete configuration, config, certifcats, etc ?
numsys - nospam - @ - nospam - .free.fr

**Comment by ktullanux** [comment]
@fredbcode send!

**Comment by fredbcode** [comment]
I'm unable to reproduce, it works well here 
I'm trying with http://yandex.ru I tried with FF and IE

**Comment by Kenny690** [comment]
@fredbcode first turn on sslmitm (in my config it's turned off, cause I'm using it on production server), and then try maps.yandex.ru or do some search.

**Comment by fredbcode** [comment]
With yandex.ru there is a redirection to google.ru 
Sorry I can't read the text before :) to me seems there is no problem

But yes I can see the issue with map, I forgot this link, ok I will investigate

**Comment by Kenny690** [comment]
Whoops, it was a workaround. :D 
You can delete everything in urlredirectregexplist and try with search. Anyway, you will get the same result as with map.

**Comment by philipianpearce** [comment]
@Kenny690 You said that it was working in v3.5.4. Was this with mitm on or off? 

Regards 

Philip 

----- Original Message -----

**Comment by Kenny690** [comment]
@philipianpearce it was always on.

**Comment by fredbcode** [comment]
Ok Philip I confirm the problem with https://yandex.ru/maps/ 
FI: This website use upgrade-insecure-requests I made a little change in code because this header can be anywhere and the first part of loop is only sequential:

1) There is upgrade-insecure-request and it is removed to browser answer
2) We have No header recd from client
3) We have SSL read failure code 1

@kenny690 I know why you have a problem with systemd, my test machine is 100% when e2 is starting, there is a timeout and systemd "think" that e2 is dead

**Comment by fredbcode** [comment]
Please try https://github.com/e2guardian/e2guardian/blob/v4.0/data/scripts/e2guardian.service.in
I don't known why E2 is so slow at start but this is not related with SSLMITM (same with off)

**Comment by fredbcode** [comment]
Philip, I can share with you the file from ktullanux if you are unable to reproduce ?

**Comment by philipianpearce** [comment]
Yes please, off-forum. 

Regards 

Philip 

----- Original Message -----

**Comment by spikedrba** [comment]
@fredbcode what's up with systemd? I'm on xenial and never had that issue, e2g uses barely 0.3% of my CPU and starts immediately.

**Comment by Kenny690** [comment]
I tried script above. Nothing happened. Maybe I should reinstall it or open another issue just to not flooding this.

**Comment by fredbcode** [comment]
@Kenny690 E2guardian stop, start, well ?
@spikedrba No problem at all, just the config files from kenny are slow at start and I guess in some case there are a timeout

**Comment by Kenny690** [comment]
@fredbcode woah, found something new. It's all the same, but service e2guardian start gives me this:

`Apr 12 11:41:41 osiris kernel: [31231.589102] cgroup: fork rejected by pids cont                                                                                                                                                             roller in /system.slice/e2guardian.service
`

**Comment by fredbcode** [comment]
Can you copy/past here your e2guardian.service please

**Comment by Kenny690** [comment]
I was using the last you suggested me.

```
[Unit]
Description=E2guardian Web filtering
After=network.target
TimeoutStartSec=20

[Service]
LimitNOFILE=65535
Type=forking
IgnoreSIGPIPE=no
GuessMainPID=no
ExecStart=@DGBINDIR@/e2guardian
ExecReload=@DGBINDIR@/e2guardian -r

[Install]
WantedBy=multi-user.target
```

**Comment by fredbcode** [comment]
:) Please just change @DGBINDIR@ by /usr/sbin/
After that systemctl daemon-reload 
And all should works now

**Comment by Kenny690** [comment]
I did that. Without that systemctl daemon-reload doesn't work.  :)

**Comment by fredbcode** [comment]
Ok and now ? stop, start, restart works ?

**Comment by Kenny690** [comment]
Sorry for my English.
I meant that:
1. Yesterday you post this message:
> Please try https://github.com/e2guardian/e2guardian/blob/v4.0/data/scripts/e2guardian.service.in
> I don't known why E2 is so slow at start but this is not related with SSLMITM (same with off)
2. I copied it, and changed @DGBINDIR@ by /usr/sbin/.
3. Did systemctl daemon-reload.
4. After that I tried to do service e2guardian restart. It returns me an error and in logs I can see message "I seem to be running already".
5. Tried to do service e2guardian stop. This command gives me absolutely nothing in logs and in return.
6. Tried to do reboot. Nothing changes. 
7. Did killall e2guardian and then service e2guardian start. After that I've got in syslog this:
`Apr 12 11:41:41 osiris kernel: [31231.589102] cgroup: fork rejected by pids cont roller in /system.slice/e2guardian.service`
And no connection to proxy. 
8. Right after that I wrote e2guardian, hit enter and got internet. 
Seems like command service e2guardian start|stop|restart can't stop the service, nor start it.

**Comment by fredbcode** [comment]
Can you copy/past again your e2guardian.service

**Comment by fredbcode** [comment]
An also try systemctl e2guardian enable

**Comment by Kenny690** [comment]
```
[Unit]
Description=E2guardian Web filtering
After=network.target
TimeoutStartSec=20

[Service]
LimitNOFILE=65535
Type=forking
IgnoreSIGPIPE=no
GuessMainPID=no
ExecStart=/usr/sbin/e2guardian
ExecReload=/usr/sbin/e2guardian -r

[Install]
WantedBy=multi-user.target
```
It's in /etc/systemd/system/e2guardian.service. Right?
I tried systemctl enable e2guardian. I'm getting this output:

```
Synchronizing state of e2guardian.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable e2guardian

```
And no difference.

**Comment by fredbcode** [comment]
Yes seems right, no problem here

**Comment by philipianpearce** [comment]
@ktullanux and @Kenny690
yandex.ru related bugs #206 and #207 are now fixed in v4.0 branch.   Please can you test and let me know the result?

Thanks, Philip

**Comment by fredbcode** [comment]
Works well here

**Comment by Kenny690** [comment]
Can't "make install" it.
```

Socket.cpp:(.text+0xa95): undefined reference to `SSLv23_client_method'
e2guardian-Socket.o: In function `Socket::checkCertHostname(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Socket.cpp:(.text+0x1180): undefined reference to `sk_num'
Socket.cpp:(.text+0x11a7): undefined reference to `sk_value'
Socket.cpp:(.text+0x138c): undefined reference to `sk_pop_free'
e2guardian-Socket.o: In function `Socket::startSslServer(x509_st*, evp_pkey_st*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
Socket.cpp:(.text+0x1775): undefined reference to `SSLv23_server_method'
e2guardian-FatController.o: In function `init_ssl_locks()':
FatController.cpp:(.text+0x5c1): undefined reference to `CRYPTO_num_locks'
FatController.cpp:(.text+0x5f3): undefined reference to `CRYPTO_num_locks'
FatController.cpp:(.text+0x63a): undefined reference to `CRYPTO_set_locking_callback'
e2guardian-FatController.o: In function `kill_ssl_locks()':
FatController.cpp:(.text+0x64f): undefined reference to `CRYPTO_set_locking_callback'
FatController.cpp:(.text+0x65b): undefined reference to `CRYPTO_num_locks'
e2guardian-FatController.o: In function `fc_controlit()':
FatController.cpp:(.text+0x7589): undefined reference to `SSL_load_error_strings'
FatController.cpp:(.text+0x758e): undefined reference to `OPENSSL_add_all_algorithms_noconf'
FatController.cpp:(.text+0x7593): undefined reference to `OpenSSL_add_all_digests'
FatController.cpp:(.text+0x7598): undefined reference to `SSL_library_init'
e2guardian-CertificateAuthority.o: In function `CertificateAuthority::getSerial(char const*, ca_serial*)':
CertificateAuthority.cpp:(.text+0x3b0): undefined reference to `EVP_MD_CTX_init'
CertificateAuthority.cpp:(.text+0x4a5): undefined reference to `EVP_MD_CTX_cleanup'
e2guardian-CertificateAuthority.o: In function `CertificateAuthority::getServerPkey()':
CertificateAuthority.cpp:(.text+0x1181): undefined reference to `CRYPTO_add_lock'
collect2: error: ld returned 1 exit status
socket.cpp:(.text+0xa95): undefined reference to `SSLv23_client_method'e2guardian-Socket.o: In function `Socket::checkCertHostname(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':Socket.cpp:(.text+0x1180): undefined reference to `sk_num'Socket.cpp:(.text+0x11a7): undefined reference to `sk_value'Socket.cpp:(.text+0x138c): undefined reference to `sk_pop_free'e2guardian-Socket.o: In function `Socket::startSslServer(x509_st*, evp_pkey_st*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':Socket.cpp:(.text+0x1775): undefined reference to `SSLv23_server_method'e2guardian-FatController.o: In function `init_ssl_locks()':FatController.cpp:(.text+0x5c1): undefined reference to `CRYPTO_num_locks'FatController.cpp:(.text+0x5f3): undefined reference to `CRYPTO_num_locks'FatController.cpp:(.text+0x63a): undefined reference to `CRYPTO_set_locking_callback'e2guardian-FatController.o: In function `kill_ssl_locks()':FatController.cpp:(.text+0x64f): undefined reference to `CRYPTO_set_locking_callback'FatController.cpp:(.text+0x65b): undefined reference to `CRYPTO_num_locks'e2guardian-FatController.o: In function `fc_controlit()':FatController.cpp:(.text+0x7589): undefined reference to `SSL_load_error_strings'FatController.cpp:(.text+0x758e): undefined reference to `OPENSSL_add_all_algorithms_noconf'FatController.cpp:(.text+0x7593): undefined reference to `OpenSSL_add_all_digests'FatController.cpp:(.text+0x7598): undefined reference to `SSL_library_init'e2guardian-CertificateAuthority.o: In function `CertificateAuthority::getSerial(char const*, ca_serial*)':CertificateAuthority.cpp:(.text+0x3b0): undefined reference to `EVP_MD_CTX_init'CertificateAuthority.cpp:(.text+0x4a5): undefined reference to `EVP_MD_CTX_cleanup'e2guardian-CertificateAuthority.o: In function `CertificateAuthority::getServerPkey()':CertificateAuthority.cpp:(.text+0x1181): undefined reference to `CRYPTO_add_lock'collect2: error: ld returned 1 exit status
```

**Comment by Kenny690** [comment]
Can't make it.
```

Socket.cpp:(.text+0xa95): undefined reference to `SSLv23_client_method'
e2guardian-Socket.o: In function `Socket::checkCertHostname(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Socket.cpp:(.text+0x1180): undefined reference to `sk_num'
Socket.cpp:(.text+0x11a7): undefined reference to `sk_value'
Socket.cpp:(.text+0x138c): undefined reference to `sk_pop_free'
e2guardian-Socket.o: In function `Socket::startSslServer(x509_st*, evp_pkey_st*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
Socket.cpp:(.text+0x1775): undefined reference to `SSLv23_server_method'
e2guardian-FatController.o: In function `init_ssl_locks()':
FatController.cpp:(.text+0x5c1): undefined reference to `CRYPTO_num_locks'
FatController.cpp:(.text+0x5f3): undefined reference to `CRYPTO_num_locks'
FatController.cpp:(.text+0x63a): undefined reference to `CRYPTO_set_locking_callback'
e2guardian-FatController.o: In function `kill_ssl_locks()':
FatController.cpp:(.text+0x64f): undefined reference to `CRYPTO_set_locking_callback'
FatController.cpp:(.text+0x65b): undefined reference to `CRYPTO_num_locks'
e2guardian-FatController.o: In function `fc_controlit()':
FatController.cpp:(.text+0x7589): undefined reference to `SSL_load_error_strings'
FatController.cpp:(.text+0x758e): undefined reference to `OPENSSL_add_all_algorithms_noconf'
FatController.cpp:(.text+0x7593): undefined reference to `OpenSSL_add_all_digests'
FatController.cpp:(.text+0x7598): undefined reference to `SSL_library_init'
e2guardian-CertificateAuthority.o: In function `CertificateAuthority::getSerial(char const*, ca_serial*)':
CertificateAuthority.cpp:(.text+0x3b0): undefined reference to `EVP_MD_CTX_init'
CertificateAuthority.cpp:(.text+0x4a5): undefined reference to `EVP_MD_CTX_cleanup'
e2guardian-CertificateAuthority.o: In function `CertificateAuthority::getServerPkey()':
CertificateAuthority.cpp:(.text+0x1181): undefined reference to `CRYPTO_add_lock'
collect2: error: ld returned 1 exit status
socket.cpp:(.text+0xa95): undefined reference to `SSLv23_client_method'e2guardian-Socket.o: In function `Socket::checkCertHostname(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':Socket.cpp:(.text+0x1180): undefined reference to `sk_num'Socket.cpp:(.text+0x11a7): undefined reference to `sk_value'Socket.cpp:(.text+0x138c): undefined reference to `sk_pop_free'e2guardian-Socket.o: In function `Socket::startSslServer(x509_st*, evp_pkey_st*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':Socket.cpp:(.text+0x1775): undefined reference to `SSLv23_server_method'e2guardian-FatController.o: In function `init_ssl_locks()':FatController.cpp:(.text+0x5c1): undefined reference to `CRYPTO_num_locks'FatController.cpp:(.text+0x5f3): undefined reference to `CRYPTO_num_locks'FatController.cpp:(.text+0x63a): undefined reference to `CRYPTO_set_locking_callback'e2guardian-FatController.o: In function `kill_ssl_locks()':FatController.cpp:(.text+0x64f): undefined reference to `CRYPTO_set_locking_callback'FatController.cpp:(.text+0x65b): undefined reference to `CRYPTO_num_locks'e2guardian-FatController.o: In function `fc_controlit()':FatController.cpp:(.text+0x7589): undefined reference to `SSL_load_error_strings'FatController.cpp:(.text+0x758e): undefined reference to `OPENSSL_add_all_algorithms_noconf'FatController.cpp:(.text+0x7593): undefined reference to `OpenSSL_add_all_digests'FatController.cpp:(.text+0x7598): undefined reference to `SSL_library_init'e2guardian-CertificateAuthority.o: In function `CertificateAuthority::getSerial(char const*, ca_serial*)':CertificateAuthority.cpp:(.text+0x3b0): undefined reference to `EVP_MD_CTX_init'CertificateAuthority.cpp:(.text+0x4a5): undefined reference to `EVP_MD_CTX_cleanup'e2guardian-CertificateAuthority.o: In function `CertificateAuthority::getServerPkey()':CertificateAuthority.cpp:(.text+0x1181): undefined reference to `CRYPTO_add_lock'collect2: error: ld returned 1 exit status
```

Maybe I missed something? I used this guide:
https://github.com/e2guardian/e2guardian/blob/v4.0/INSTALL

**Comment by fredbcode** [comment]
Which OS ? Did you make ./autgen.sh and ./configure --option ?

**Comment by Kenny690** [comment]
Debian Stretch. 
Of course, I followed the guide. 
My options:
` ./configure '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-sslmitm=yes' '--enable-pcre=yes'`

**Comment by fredbcode** [comment]
It's like libssl-dev and libssl1.0.0 are missing

**Comment by Kenny690** [comment]
I have libssl-dev (1.1.0e-1) and libssl1.0.0 (1.0.1t-1+deb8u6).

**Comment by ktullanux** [comment]
build branch v4.0 on test server and yandex maps, search and other works well! :3

**Comment by Kenny690** [comment]
Besides, I can install deb. But it's from v4.0beta2 branch.

**Comment by fredbcode** [comment]
Kenny690 can try pull github now and post here the returns from ./configure ...

**Comment by fredbcode** [comment]
No package now, and it is only tested on stable release, not testing

**Comment by fredbcode** [comment]
Ok install "libssl1.0-dev" and try what I wrote before

**Comment by Kenny690** [comment]
```
root@Osiris:~/e2guardian# ./configure '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-sslmitm=yes' '--enable-pcre=yes' 0
configure: WARNING: you should use --build, --host, --target
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/bash: /root/e2guardian/missing: No such file or directory
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for 0-g++... no
checking for 0-c++... no
checking for 0-gpp... no
checking for 0-aCC... no
checking for 0-CC... no
checking for 0-cxx... no
checking for 0-cc++... no
checking for 0-cl.exe... no
checking for 0-FCC... no
checking for 0-KCC... no
checking for 0-RCC... no
checking for 0-xlC_r... no
checking for 0-xlC... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking dependency style of g++... (cached) gcc3
checking for 0-gcc... no
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... ^Croot@Osiris:~/e2guardian# ./configure '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enabletlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-sslmitm=yes' '--enable-pcre=yes'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/bash: /root/e2guardian/missing: No such file or directory
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking dependency style of g++... (cached) gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for sys/types.h... (cached) yes
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking sys/poll.h usability... yes
checking sys/poll.h presence... yes
checking for sys/poll.h... yes
checking sys/epoll.h usability... yes
checking sys/epoll.h presence... yes
checking for sys/epoll.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking grp.h usability... yes
checking grp.h presence... yes
checking for grp.h... yes
checking byteswap.h usability... yes
checking byteswap.h presence... yes
checking for byteswap.h... yes
checking whether byte ordering is bigendian... no
checking if zlib should be statically linked... no
checking for zlib... checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for gzdopen in -lz... yes
yes
checking for pid_t... yes
checking for size_t... yes
checking for off_t... yes
checking for uid_t in sys/types.h... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for dup2... yes
checking for gettimeofday... yes
checking for memset... yes
checking for select... yes
checking for strerror... yes
checking for strstr... yes
checking for strtol... yes
checking for setuid... yes
checking for setgid... yes
checking for umask... yes
checking for seteuid... yes
checking for setreuid... yes
checking for setlocale... yes
checking for library containing floor... none required
checking for library containing gethostbyname... none required
checking for library containing socket... none required
checking for library containing inet_aton... none required
checking for backside with both hands... no
checking build os... checking build system type... x86_64-pc-linux-gnu
linux-gnu
checking for debug option... no
checking for proxy user... yes
checking for proxy group... yes
checking for piddir... no
checking for logdir... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for PCRE support... yes
checking for PCRE... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
Version: 20170406
checking for backtrace on segfault support... no
checking for large file support... yes
checking for original destination IP checking support... no
checking for type collision with off_t... yes
checking for clamd support... yes
checking for avastd support... no
checking for icap support... yes
checking for kavd support... no
checking for command-line content scanner support... yes
checking for fancy download manager support... yes
checking for trickle download manager support... yes
checking for NTLM support... yes
checking for iconv... yes
native
checking for SSL MITM support... yes
checking for OPENSSL... yes
checking for DNS support... no
checking for email notification support... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating data/Makefile
config.status: creating data/languages/Makefile
config.status: creating data/scripts/Makefile
config.status: creating data/scripts/bsd-init
config.status: creating data/scripts/e2guardian
config.status: creating data/scripts/logrotation
config.status: creating data/scripts/solaris-init
config.status: creating data/scripts/systemv-init
config.status: creating data/scripts/e2guardian.service
config.status: creating doc/Makefile
config.status: creating configs/e2guardian.conf
config.status: creating configs/e2guardianf1.conf
config.status: creating configs/Makefile
config.status: creating configs/lists/Makefile
config.status: creating configs/lists/phraselists/Makefile
config.status: creating configs/lists/bannedrooms/Makefile
config.status: creating configs/lists/contentscanners/Makefile
config.status: creating configs/lists/bannedphraselist
config.status: creating configs/lists/bannedurllist
config.status: creating configs/lists/bannedsitelist
config.status: creating configs/lists/exceptionphraselist
config.status: creating configs/lists/weightedphraselist
config.status: creating configs/downloadmanagers/Makefile
config.status: creating configs/downloadmanagers/default.conf
config.status: creating configs/downloadmanagers/fancy.conf
config.status: creating configs/downloadmanagers/trickle.conf
config.status: creating configs/contentscanners/Makefile
config.status: creating configs/contentscanners/clamdscan.conf
config.status: creating configs/contentscanners/avastdscan.conf
config.status: creating configs/contentscanners/icapscan.conf
config.status: creating configs/contentscanners/kavdscan.conf
config.status: creating configs/contentscanners/commandlinescan.conf
config.status: creating configs/authplugins/Makefile
config.status: creating configs/authplugins/ip.conf
config.status: creating configs/authplugins/port.conf
config.status: creating configs/lists/authplugins/Makefile
config.status: creating configs/lists/downloadmanagers/Makefile
config.status: creating src/Makefile
config.status: creating dgconfig.h
config.status: dgconfig.h is unchanged
config.status: executing depfiles commands

```

**Comment by Kenny690** [comment]
Works now!

**Comment by fredbcode** [comment]
No, you can try to install the previous package and switch the binary

**Comment by Kenny690** [comment]
Whoops, sorry, Just wanted to say, that it works.

**Comment by fredbcode** [comment]
@philipianpearce some functions got deprecated with OpenSSL 1.1.0, I wrote some words in INSTALL for Debian and Ubuntu 

You can realease when you want

**Comment by Kenny690** [comment]
I forgot to add. When you doing apt-get install libssl1.0-dev - it removes libssl-dev (so this package is not needed anymore) and libclamav-dev (IDK why).

**Comment by philipianpearce** [comment]
OK, v4.1.0 released. 

Regards 

Philip 

----- Original Message -----
