### ISSUE TITLE
clamdscan

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#296]
Using v5develop, can't get clamav to work properly.  Compiled it with enable-clamd and having the following config files -

e2guardian.conf
contentscanner = '/etc/e2guardian/contentscanners/clamdscan.conf'

and
clamdscan.conf
clamdudsfile = '/var/run/clamav/clamd.sock'

The issue is that it never invokes clamdscan.  The test file is eicar.

**Comment by fredbcode** [comment]
Hum the last time I tried there was a compilation error with AV.
Not for you ?

Le 29 octobre 2017 01:42:05 GMT+02:00, dbrody2004 <notifications@github.com> a écrit :
>Using v5develop, can't get clamav to work properly.  Compiled it with
>enable-clamd and having the following config files -
>
>e2guardian.conf
>contentscanner = '/etc/e2guardian/contentscanners/clamdscan.conf'
>
>and
>clamdscan.conf
>clamdudsfile = '/var/run/clamav/clamd.sock'
>
>The issue is that it never invokes clamdscan.  The test file is eicar. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/296

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by philipianpearce** [comment]
Note that v5develop is still work in progress and a number of features (including download plugins) are not yet implemented. 

Please refer to https://github.com/e2guardian/e2guardian/blob/v5develop/notes/NEWIN_v5 to see what features are currently testable. 

You will find download plugins is in the TODO list! 

Regards 

Philip 

----- Original Message -----

**Comment by fredbcode** [comment]
Which version ?

Le 28 novembre 2017 01:41:58 GMT+01:00, dbrody2004 <notifications@github.com> a écrit :
>I noticed that the task "Enable download/anti-virus plugins" was
>removed from the notes.  I enabled clamav and it still gives the error
>- "Exception whilst writing to ClamD socket: 0 TimedOut".  I did notice
>in the notes "Anti-virus plugins implimented for proxy, trans and ICAP
>- but individual plug-ins not tested".
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/296#issuecomment-347376061

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by dbrody2004** [comment]
v5develop up to the latest commit (https://github.com/e2guardian/e2guardian/commit/be186838bbe1eb2df2ef0dd956630d80d31affcc).  I made sure that clamav is running as nobody and so is e2guardian.  The clamav pid file is present.

**Comment by philipianpearce** [comment]
There is a bug in the content_scanner_timeout value handling causing premature timeout. 

I have fixed and will push to v5develop shortly. 

Regards 

Philip 

----- Original Message -----

**Comment by dbrody2004** [comment]
Still not working.  Not sure that was the issue.  The error is - "Exception whilst writing to ClamD socket: 0 TimedOut" which happens before  rc = stripedsocks.getLine(buff, 4096, o.content_scanner_timeout); in clamdscan.cpp.  The change affected content_scanner_timeout.

Debug log - 
[2.txt](https://github.com/e2guardian/e2guardian/files/1516930/2.txt)

**Comment by philipianpearce** [comment]
This error means that e2g was unable to write to the socket and stopped after trying for the default timeout of 5 secs. 

Suggest you check permissions on the unix socket path and also that clamd is listening on that socket. 

Regards 

Philip 

----- Original Message -----

**Comment by dbrody2004** [comment]
Found the issues.

First - clamdscan.cpp creates a UDSocket, connects to it and calls stripedsocks.writeString.  BaseSocket writeString calls breadyForOutput which calls poll(outfds, 1, timeout);  outfds and infds are never initialized in the UDSocket constructor and reset routines - it is in there for version 4, but removed for v5_develop.

Second - e2guardian runs as nobody.  The tmp file that is created for clamd has permissions 440 nobody:nogroup.  Clam daemon runs as clamav:clamav which can't access the tmp file.  Probably a better solution is to chmod to include S_IROTH in the chmod stamement within clamdscan.cpp.

**Comment by fredbcode** [comment]
For the second issue you can very easily change the rights

Eg:
/etc/clamav/clamd.conf -> User e2guardian
/etc/e2guardian/e2guardian.conf -> deamonuser = 'e2guardian' and there is also deamongroup if needed.

I think no needs to play with the code because there is no definitive rule, each implementation will be different (Suse, freebsd, debian, etc)

Philip, maybe we should add a more explicit message 

"Exception whilst writing to ClamD socket: 0 TimedOut" -> Add few words about "access rights"

**Comment by philipianpearce** [comment]
Poll not working now fixed in v5develop.

A agree with Fred re the file permissions.

To allow clamd to access the temporary file just make the clamd user a member of the same group as e2guardian.  You do not need to touch either the e2g or clamd configurations to do this.   Just add clamd user to list of users of e2guardian group in /etc/groups - by whatever method is recommended on your os platform.
