### ISSUE TITLE
v5_develop - [inet_ntoa error] trunked on logs

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#380]
trying to run sarg on e2guardian access logs in squid format, I'm getting different sizes and spaces when [inet_ntoa error] is logged.

attached and below, some examples of it's output

1526317928.292   5650 **[inet_.1.137** TCP_MISS/0 23573 CONNECT https://clientservices.googleapis.com:443 172.17.1.137 DEFAULT_PARENT/ -
1525882401.748  20045 **[inet_nt.16** TCP_MISS/0 183 CONNECT https://pixel.mathtag.com:443 mat00671 DEFAULT_PARENT/ -
1525690669.110      0 **[inet_ntoa**  TCP_DENIED/403 0 CONNECT https://arc.msn.com:443 172.17.1.35 DEFAULT_PARENT/ -
1526072769.056      0 **[inet_nto47** TCP_DENIED/403 0 GET http://tile-service.weather.microsoft.com/pt-BR/livetile/preinstall?region=BR&appid=C98EA5B0842DBB9405BBF071E1DA76512D21FE36&FORM=Threshold 172.17.1.47 DEFAULT_PARENT/ -
1525692344.282    297 **[inet_ntoa error]** TCP_MISS/200 12101 GET http://inveniowebservices.robbu.com.br/handlerarquivo.ashx?idarquivo=1DA2E85F9A955359&origem=1 DIGITAL DEFAULT_PARENT/ -
[output_e2guardian.txt](https://github.com/e2guardian/e2guardian/files/2002715/output_e2guardian.txt)

**Comment by philipianpearce** [comment]
I have pushed a potential fix to v5develop. 

Can you let me know if it works for you. 

Thanks 

Philip 

----- Original Message -----

**Comment by marcelloc** [comment]
Thanks for the fast response. I've compiled today and testing...

**Comment by marcelloc** [comment]
seems to be still happening

1526727176.144  53240 [inet_ntoa  TCP_MISS/0 42440 CONNECT https://settings-win.data.microsoft.com:443
1526731233.429  25213 [inet_ntoa  TCP_MISS/0 3282 CONNECT https://fonts.gstatic.com:443
1526900743.443      0 [ine17.1.148 TCP_DENIED/403 0 CONNECT https://login.live.com:443
1526907296.170      0 [inet_ntoa  TCP_DENIED/403 0 GET http://tile-service.weather.microsoft.com/pt-BR
1526910415.078      0 [inet_ntoa  TCP_DENIED/403 0 CONNECT https://connect.facebook.net:443
1526908922.301   5000 [inet_ntoa e TCP_DENIED/403 0 CONNECT https://pixel.mathtag.com:443

**Comment by philipianpearce** [comment]
What platform are you using Linux/FreeBSD etc and version? 

Is this on all log lines or just a few? 

What settings are you using for reverseaddresslookups, reverseclientiplookups, and logclienthostnames? 

Regards 

Philip 

----- Original Message -----

**Comment by marcelloc** [comment]
**What platform are you using Linux/FreeBSD etc and version?**
I'm using on pfSense/Freebsd 11 

**Is this on all log lines or just a few?**
Just few lines are truncated. most network erros are logged fine.

**What settings are you using for reverseaddresslookups, reverseclientiplookups, and logclienthostnames?**
reverseaddresslookups = off
reverseclientiplookups = off
logclienthostnames = off

**Comment by philipianpearce** [comment]
Hi, 

I have tracked the issue down - inet_ntoa() is not thread-safe in freeBSD so these calls need changing to a thread-safe call. 

I will not be able to look at this for a few weeks, but if someone else is able too in the meantime that would be great? 

Regards 

Philip 

----- Original Message -----

**Comment by philipianpearce** [comment]
Hi, 

Can you check latest v5.1 for fix on freeBSD?

Thanks
Philip

**Comment by marcelloc** [comment]
Compiled fine (didn't looked for any docker compile option), just the options I used on 5.0

I'll test tomorrow with more concurrent connections to see how inet erros are logged.

**Comment by fredbcode** [comment]
I can close ?
