### ISSUE TITLE
v5.4 sslreplace not working in ICAP mode

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#642]
Raised from #638.    sslreplace is set in storyboard trace but not actioned in ICAP mode.

**Comment by philipianpearce** [comment]
@puppetmaster

Can you try latest v5.4.dev?  I have pushed a fix for this in ICAP mode.

Philip

**Comment by puppetmaster** [comment]
Yes I can, I will build it now and try this afternoon.

**Comment by puppetmaster** [comment]
I suppose I have to enable sslbump or MITM support ?

At this point with default configuration without sslbump or MITM still don't work for me. Youtube is not in safemode.

**Comment by fredbcode** [comment]
No SSLMITM is not needed in this specific case

You can try with ICAP

You can also take a look here https://e2guardian.numsys.eu v5.4.dev for 
packages

**Comment by puppetmaster** [comment]
Sorry, for the delay.

I have tested this package : https://e2guardian.numsys.eu/v5.4.dev/e2ubuntu_focal_V5.4.3_20201124.deb

Is this the version in need of testing ?

sslreplace don't work for me.

The logs : 
```
==> /var/log/rsyslog/local/squid/squid1.info.log <==
2020-12-11T10:59:20.794975+01:00 amon.etb1.lan squid[21783]: 1607680760.794     21 10.1.2.50 TCP_DENIED/407 4072 CONNECT www.youtube.com:443 - HIER_NONE/- text/html
2020-12-11T10:59:20.800347+01:00 amon.etb1.lan squid[21783]: 1607680760.798      1 10.1.2.50 TCP_DENIED/407 4404 CONNECT www.youtube.com:443 - HIER_NONE/- text/html

==> /var/log/e2guardian/debuge2 <==
hw43: 1607680760 ICAP debug : hw43: firstime: ICAPheader:in after getLine

hw43: 1607680760 ICAP debug : hw43: Returning from header:in client requests with ICAP length: 46 content: REQMOD icap://127.0.0.1:1340/request ICAP/1.0

hw43: 1607680760 ICAP debug : hw43: Request is icap://127.0.0.1:1340/request size: 46 content: REQMOD icap://127.0.0.1:1340/request ICAP/1.0

hw43: 1607680760 ICAP debug : hw43: Request method is: REQMOD error?:  url value: request

allow_204 is 0 allow_206 is 0 hw43: Header value from ICAP client: Host: 127.0.0.1:1340

allow_204 is 0 allow_206 is 0 hw43: Header value from ICAP client: Date: Fri, 11 Dec 2020 09:59:20 GMT

hw43: 1607680760 ICAP debug : hw43: Header value from ICAP client: Proxy-Authorization: NTLM TlRMTVNTUAADAAAAGAAYAIYAAAAQARABngAAABIAEgBYAAAACgAKAGoAAAASABIAdAAAAAAAAACuAQAABYKIogoAYUoAAAAP+3IPSEWaskMPJNDUflxEVkQATwBNAFAARQBEAEEARwBPAGEAZABtAGkAbgBQAEMALQA0ADUAOQA3ADgANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqeu7rYDFeZ046pCgkjZOqAQEAAAAAAADsF9dLpM/WARr3IptVoFBrAAAAAAIAEgBEAE8ATQBQAEUARABBAEcATwABAAgAQQBNAE8ATgAEABAAZQB0AGIAMQAuAGwAYQBuAAMAGgBhAG0AbwBuAC4AZQB0AGIAMQAuAGwallow_204 is 0 allow_206 is 0AAAACAAwADAAAAAAAAAAAQAAAAAgAADCO6cXpXKwaG/ULI47XH+wCQnm9xSbOLCPNJdmzwwgGAoAEAAAAAAAAAAAAAAAAAAAAAAACQAoAEgAVABUAFAALwB3AHcAdwAuAHkAbwB1AHQAdQBiAGUALgBjAG8AbQAAAAAAAAAAAA==

hw43: 1607680760 ICAP debug : hw43: pencapsulated is Encapsulated: req-hdr=0, null-body=159

allow_204 is 0 allow_206 is 0 hw43: Header value from ICAP client: Encapsulated: req-hdr=0, null-body=159

allow_204 is 1 allow_206 is 0 hw43: Header value from ICAP client: Allow: 204

allow_204 is 1 allow_206 is 0 hw43: Header value from ICAP client: X-Client-IP: 10.1.2.50

allow_204 is 1 allow_206 is 0 hw43: Header value from ICAP client: X-Authenticated-User: YWRtaW4=

hw43: 1607680760 ICAP debug : hw43: checkheader done- 2 encap_recs

hw43: 1607680760 ICAP debug : hw43: service options enabled :  icaphead.service_reqmod: 1 icaphead.service_resmod: 0 icaphead.service_options:  icaphead.icap_reqmod_service: 1 icaphead.icap_resmod_service: 0 icaphead.icap_reqmod_service: 1

hw43: 1607680760 ICAP debug : hw43: Icap reqmod check

hw43: 1607680760 ICAP debug : hw43: -username: - ICAP -filtergroup: 1

hw43: 1607680760 ICAP debug : hw43: ICAP response starting - RCode 200 OK echo is 1

hw43: 1607680760 ICAP debug : hw43: out_req_header copied from HTTPrequest :CONNECT :443 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
Host:



hw43: 1607680760 ICAP debug : hw43: Icap response header is: ICAP/1.0 200 OK
ISTag:1607679213
X-ICAP-E2G:-,G,0,0,0,
Encapsulated: req-hdr=0, null-body=125

CONNECT :443 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
Host:



hw43: 1607680760 ICAP debug : hw43: Returning from icapheader:respond

hw43: 1607680760 ICAP debug : hw43:  ICAP -persisting (count 239) Client IP: 127.0.0.1

hw43: 1607680760 ICAP debug : hw43: Start of request ICAPheader:in

hw43: 1607680760 ICAP debug : hw43: ICAPheader:in before getLine - timeout: 120000


==> /var/log/rsyslog/local/e2guardian/e2guardian0.info.log <==
2020-12-11T10:59:20.809199+01:00 amon.etb1.lan e2guardian0[19543]: "2020.12.11 10:59:20","-","10.1.2.50","https://restrict.youtube.com:443","*URLMOD* -","CONNECT","0","0","-","1","0","-","10.1.2.50","politiquedefaut","-","-","-","-","-"

==> /var/log/rsyslog/local/squid/squid1.info.log <==
2020-12-11T10:59:20.811728+01:00 amon.etb1.lan squid[21783]: 1607680760.808      0 10.1.2.50 NONE/000 0 NONE www.youtube.com:443 admin HIER_NONE/- -

==> /var/log/e2guardian/debuge2 <==
hw43: 1607680760 ICAP debug : hw43: firstime: ICAPheader:in after getLine

hw43: 1607680760 ICAP debug : hw43: firstime: ICAPheader:in after getLine: rc: -1 truncated: 0

hw43: 1607680760 ICAP debug : hw43:  -ICAP Persistent connection closed

hw43: 1607680760 ICAP debug : hw43: ICAP -Attempting graceful connection close


==> /var/log/rsyslog/local/squid/squid1.info.log <==
2020-12-11T10:59:20.812037+01:00 amon.etb1.lan squid[21783]: 1607680760.811     11 10.1.2.50 NONE/500 3477 CONNECT www.youtube.com:443 admin HIER_NONE/- text/html

==> /var/log/e2guardian/debuge2 <==
hw178: 1607680767 ICAP debug : hw178: firstime: ICAPheader:in after getLine

hw178: 1607680767 ICAP debug : hw178: Returning from header:in client requests with ICAP length: 48 content: OPTIONS icap://127.0.0.1:1340/response ICAP/1.0

hw178: 1607680767 ICAP debug : hw178: Request is icap://127.0.0.1:1340/response size: 48 content: OPTIONS icap://127.0.0.1:1340/response ICAP/1.0

hw178: 1607680767 ICAP debug : hw178: Request method is: OPTIONS error?:  url value: response

allow_204 is 0 allow_206 is 0: hw178: Header value from ICAP client: Host: 127.0.0.1:1340

allow_204 is 0 allow_206 is 1: hw178: Header value from ICAP client: Allow: 206

hw178: 1607680767 ICAP debug : hw178: checkheader done- 0 encap_recs

hw178: 1607680767 ICAP debug : hw178: service options enabled :  icaphead.service_reqmod: 0 icaphead.service_resmod: 0 icaphead.service_options:  icaphead.icap_reqmod_service: 0 icaphead.icap_resmod_service: 1 icaphead.icap_reqmod_service: 0

hw178: 1607680767 ICAP debug : hw178: respmod service options response : ICAP/1.0 200 OK
Methods: RESPMOD
Service: e2guardian 5.4.3
ISTag:1607679213
Encapsulated: null-body=0
Allow: 204



hw178: 1607680767 ICAP debug : hw178:  ICAP -persisting (count 31) Client IP: 127.0.0.1

hw178: 1607680767 ICAP debug : hw178: Start of request ICAPheader:in

hw178: 1607680767 ICAP debug : hw178: ICAPheader:in before getLine - timeout: 120000


==> /var/log/rsyslog/local/squid/squid1.info.log <==
2020-12-11T10:59:27.654778+01:00 amon.etb1.lan squid[21783]: 1607680767.654      0 - NONE/000 0 NONE - - HIER_NONE/- -

```

Produces : 

![shot-2020-12-11_10-56-50](https://user-images.githubusercontent.com/101515/101889449-b2c49a80-3b9f-11eb-9cb8-48355afb9742.jpg)

**Comment by philipianpearce** [comment]
I have replicated this issue and have further corrected the code so that e2g now gives correct output to squid in icap mode.
However, in my test system, squid does not act on the change to the CONNECT site correctly and we are still getting the same error returned to the browser.

So, e2g in reqmod now works as expected, but squid appears to ignore it.   

As this is the case I have commented out the storyboard call in common.story to disable this function.  If a squid expert is wants to try changing squid config in some way to make it work, then the lines can be uncommented.

It may be that the only way to get this to work in ICAP mode is change the squid DNS look-up in the way recommended by Google for google/youtube restricted search.

Summary:   **BUG fixed - but problem not solved - work rounds exist**
